// Generated by upstream Rustly from hello.clj; do not edit.
fn greeting() {
uart_write(b"\nHello, world from Rustly Clojure on Raspberry Pi 4!\n");
uart_write(b"Clojure -> Rust -> ARM64. No OS, no heap.\n");
uart_write(b"Type letters/digits to blink Morse; empty line stops.\n> ");
}
fn accepted() {
uart_write(b"\nRepeating Morse: ");
}
fn stopped() {
uart_write(b"\nMorse stopped.\n> ");
}
fn invalid() {
uart_write(b"\nUse up to 64 ASCII letters, digits or spaces; message unchanged.\n> ");
}
fn prompt() {
uart_write(b"\n> ");
}
fn heartbeat_on() {
board_led_on();
}
fn heartbeat_off() {
board_led_off();
}
fn configure_morse() {
register_morse(0, b".-");
register_morse(1, b"-...");
register_morse(2, b"-.-.");
register_morse(3, b"-..");
register_morse(4, b".");
register_morse(5, b"..-.");
register_morse(6, b"--.");
register_morse(7, b"....");
register_morse(8, b"..");
register_morse(9, b".---");
register_morse(10, b"-.-");
register_morse(11, b".-..");
register_morse(12, b"--");
register_morse(13, b"-.");
register_morse(14, b"---");
register_morse(15, b".--.");
register_morse(16, b"--.-");
register_morse(17, b".-.");
register_morse(18, b"...");
register_morse(19, b"-");
register_morse(20, b"..-");
register_morse(21, b"...-");
register_morse(22, b".--");
register_morse(23, b"-..-");
register_morse(24, b"-.--");
register_morse(25, b"--..");
register_morse(26, b"-----");
register_morse(27, b".----");
register_morse(28, b"..---");
register_morse(29, b"...--");
register_morse(30, b"....-");
register_morse(31, b".....");
register_morse(32, b"-....");
register_morse(33, b"--...");
register_morse(34, b"---..");
register_morse(35, b"----.");
}
