;; Rustly uses named fn forms rather than defn.
;; Calls target board functions supplied by our no_std Rust driver.
(fn greeting []
  (uart_write "\nHello, world from Rustly Clojure on Raspberry Pi 4!\n")
  (uart_write "Clojure -> Rust -> ARM64. No OS, no heap.\n")
  (uart_write "Type letters/digits to blink Morse; empty line stops.\n> "))

(fn accepted [] (uart_write "\nRepeating Morse: "))
(fn stopped [] (uart_write "\nMorse stopped.\n> "))
(fn invalid [] (uart_write "\nUse up to 64 ASCII letters, digits or spaces; message unchanged.\n> "))
(fn prompt [] (uart_write "\n> "))

(fn heartbeat_on [] (board_led_on))
(fn heartbeat_off [] (board_led_off))

;; International Morse: a-z then 0-9. Installed once before UART polling.
(fn configure_morse []
  (register_morse 0 ".-")
  (register_morse 1 "-...")
  (register_morse 2 "-.-.")
  (register_morse 3 "-..")
  (register_morse 4 ".")
  (register_morse 5 "..-.")
  (register_morse 6 "--.")
  (register_morse 7 "....")
  (register_morse 8 "..")
  (register_morse 9 ".---")
  (register_morse 10 "-.-")
  (register_morse 11 ".-..")
  (register_morse 12 "--")
  (register_morse 13 "-.")
  (register_morse 14 "---")
  (register_morse 15 ".--.")
  (register_morse 16 "--.-")
  (register_morse 17 ".-.")
  (register_morse 18 "...")
  (register_morse 19 "-")
  (register_morse 20 "..-")
  (register_morse 21 "...-")
  (register_morse 22 ".--")
  (register_morse 23 "-..-")
  (register_morse 24 "-.--")
  (register_morse 25 "--..")
  (register_morse 26 "-----")
  (register_morse 27 ".----")
  (register_morse 28 "..---")
  (register_morse 29 "...--")
  (register_morse 30 "....-")
  (register_morse 31 ".....")
  (register_morse 32 "-....")
  (register_morse 33 "--...")
  (register_morse 34 "---..")
  (register_morse 35 "----.")
)
