(require '[rustly.parse :as parser]
         '[rustly.rust-translate :as translate]
         '[rustly.rust-emit :as emit]
         '[clojure.java.io :as io])
(let [[input output] *command-line-args*
      forms (parser/read-file (or input "hello.clj"))
      output (or output "build/app.rs")]
  (io/make-parents output)
  (spit output (str "// Generated by upstream Rustly from hello.clj; do not edit.\n"
                    (apply str (map (comp emit/emit translate/translate) forms))))
  (println "Rustly generated" output))
